# One time pad with the same key problem

### The cyphers to be broken:

A84537EC762D276D2804F0051C76FBB61DA962A904055BCF56D2E08BA3

BF4334AA672868223800E103066AA8F709AF6FEC0E105CCB52D4E691BE

B85530EE332C62612B13E7570A77ECFF12BC27EE150D51CD5FC9E19BA3

A45527EF617F75672B12E7570676EDB608B26AEC401454CC13CBEA87A3

BF4035EB673A277B3114F0571A61FBE219B674A9120152DD5FC1FD92A9

A31022E272336B222913EB030C38FBF31FAE75EC40175ACE47D7EE8CB5

In [1]:
#for helping in computations.
import numpy as np

In [2]:
#The numpy array that will contain the cypher texts.
c = np.array(['A84537EC762D276D2804F0051C76FBB61DA962A904055BCF56D2E08BA3',
              'BF4334AA672868223800E103066AA8F709AF6FEC0E105CCB52D4E691BE',
              'B85530EE332C62612B13E7570A77ECFF12BC27EE150D51CD5FC9E19BA3',
              'A45527EF617F75672B12E7570676EDB608B26AEC401454CC13CBEA87A3',
              'BF4035EB673A277B3114F0571A61FBE219B674A9120152DD5FC1FD92A9',
              'A31022E272336B222913EB030C38FBF31FAE75EC40175ACE47D7EE8CB5'])

In [3]:
#Shape of the array.
c.shape

(6,)

### Now define a function to make the XOR operation.

In [95]:
def XOR(hex1, hex2):
    # Step 1: Convert hexadecimal strings to integers
    int1 = int(hex1, 16)
    int2 = int(hex2, 16)
    
    # Step 2: Perform the XOR operation
    result_int = int1 ^ int2
    
    # Step 3: Convert the result back to hexadecimal
    result_hex = format(result_int, 'X')
    
    return result_hex

### Getting the spaces in the plain text first.

In [6]:
#This function will perform the xor of each cypher text with the rest of them.
def CalculatingXors(c, index):
    result = np.array([])
    
    #Looping on the cypher texts.
    for i in range(0, 6):
        
        #don't perfrom the xoring with the same cypher text.
        if (i == index):
            continue
        result = np.append(result, XOR(c[index],c[i]))
    return result

### Getting the xor's of the cyphers.

In [7]:
#getting the first xor's
c0xor = CalculatingXors(c,0)
#adding the zeros at the first
c0xor[2] = '0C1010031752520A031617521A001600151B084544110F0345190A0C00'
c0xor[4] = '0B55150E041E4C4F01171B06104E0045020717454412010111050E0716'

#getting the second xor's
c1xor = CalculatingXors(c, 1)
#adding the zeros at the first
c1xor[1] = '0716044454040A43131306540C1D44081B1348021B1D0D060D1D070A1D'
c1xor[3] = '0003014100124F59091411541C0B531510191B451C110E160D151B0317'

#getting the third xor's
c2xor = CalculatingXors(c,2)
#adding the zeros at the first
c2xor[1] = '0716044454040A43131306540C1D44081B1348021B1D0D060D1D070A1D'
c2xor[3] = '071505055416451A1A0717001016171D0B0A5347070C031000081C090A'

#getting the fourth xor's
c3xor = CalculatingXors(c,3)
#as the first value isn't a 0
c3xor[0] = '0C1010031752520A031617521A001600151B084544110F0345190A0C00'
c3xor[4] = '0745050D134C1E4502010C540A4E1645171C1F0000030E02541C040B16'

#getting the fifth xor's
c4xor = CalculatingXors(c, 4)
#adding the zeros at the first
c4xor[1] = '0003014100124F59091411541C0B531510191B451C110E160D151B0317'
c4xor[2] = '071505055416451A1A0717001016171D0B0A5347070C031000081C090A'

#Getting the 6th xor's
c5xor = CalculatingXors(c, 5)
#getting the zeros at the first
c5xor[0] = '0B55150E041E4C4F01171B06104E0045020717454412010111050E0716'
c5xor[3] = '0745050D134C1E4502010C540A4E1645171C1F0000030E02541C040B16'

### Doing some mappings to get the position of the spaces:

In [8]:
#This function will consider a space in the place where the third bit is a 1
#or the first byte is a 0.
def spacesPosition(cxor, index):
    new_row = np.array([])
    result = []
    #looping through all the left rows, then inside each row.
    for j in range(0, 5):
        if(index == j):
            continue
        for i in range(0, 29):
            if ((cxor[j][i*2] == '4') or (cxor[j][i*2] == '5') or
                (cxor[j][i*2] == '6') or (cxor[j][i*2] == '7') or 
                (cxor[j][i*2] == 'C') or (cxor[j][i*2] == 'D') or
                (cxor[j][i*2] == 'E') or (cxor[j][i*2] == 'F') or
                (cxor[j][i*2] == '0')):
                new_row = np.append(new_row, i*2)
        result.append(new_row)
        #To reset the new row added before the next iteration.
        new_row = np.array([])
    return result

In [9]:
#saving the first mapings
c0sp = spacesPosition(c0xor, 0)

#saving the second mapings
c1sp = spacesPosition(c1xor, 1)

#saving the third mapings
c2sp = spacesPosition(c2xor, 2)

#saving the fourth mapings
c3sp = spacesPosition(c3xor, 3)

#saving the fifth mapings
c4sp = spacesPosition(c4xor, 4)

#saving the 6th position
c5sp = spacesPosition(c5xor, 5)

### Now getting the positions of the spaces.

In [10]:
#This function will return the spaces positions
def spaces(csp):
    #Initializing the spaces array
    spaces = np.array([])
    
    #Getting all the unique values inside the list first,
    #by stacking all the elemnts in a single row first
    uniq = np.hstack(csp)
    uniq = np.unique(uniq)
    
    #looping through all the unique numbers.
    for i in range(0, len(uniq)):
        # Number to check for
        number_to_check = uniq[i]
        
        
        # Initialize a result variable to True
        result = True
        
        # Check if the number exists in all arrays
        for arr in csp:
            if number_to_check not in arr:
                result = False
                break
        
        if result:
            spaces = np.append(spaces, number_to_check)
    return spaces

In [37]:
#saving the first position spaces
c0space = spaces(c0sp)
c0space = c0space.astype(int)

#saving the second position spaces
c1space = spaces(c1sp)
c1space = c1space.astype(int)

#saving the third position spaces
c2space = spaces(c2sp)
c2space = c2space.astype(int)

#saving the fourth position spaces
c3space = spaces(c3sp)
c3space = c3space.astype(int)

#saving the fifth position spaces
c4space = spaces(c4sp)
c4space = c4space.astype(int)

#saving the 6th position spaces
c5space = spaces(c5sp)
c5space = c5space.astype(int)

### Now getting part of the key:

The Idea here is to get parts of the key by xoring the position of the spaces we got, with the '20' the space in hexa

##### The positions of the spaces:

array([ 6., 12., 22., 30., 38., 44.])
array([ 6., 14., 22., 28., 38., 44.])
array([ 6.,  8., 12., 22., 36., 38., 44.])
array([ 6., 10., 14., 22., 30., 38., 40., 44., 46., 48., 52.])
array([ 6., 12., 22., 38., 44., 48.])
array([ 2.,  6., 14., 22., 26., 38., 40., 44.])
​

In [157]:
#This function takes the cypher texts, the space positions, key and the index of the cypher texts.
def keyValues(c, csp, key, index):
    
    #looping through the values of the spaces position.
    for i in range(0, len(csp)):
        
        #Getting the values from the cypher text
        x = c[index][csp[i]: csp[i] + 2]
        
        #Xoring with the space in hexa.
        y = XOR(x, '20')
        
        #adding a zero if the first value of x is a 2
        if(x[0] == '2'):
            y = '0' + y
        
        #setting the values according to the porsitions.
        key[csp[i]] = y[0]
        key[csp[i] + 1] = y[1]
        
    return key

In [158]:
#Initializing the key.
key = np.zeros(58, dtype = '<U2')

In [159]:
#Now sending the spaces posistions to get the info of the key.
key = keyValues(c, c0space, key, 0)
key = keyValues(c, c1space, key, 1)
key = keyValues(c, c2space, key, 2)
key = keyValues(c, c3space, key, 3)
key = keyValues(c, c4space, key, 4)
key = keyValues(c, c5space, key, 5)

#### Values of the key after getting the spaces

In [160]:
key

array(['', '', '3', '0', '', '', 'C', '2', '1', '3', '5', 'F', '0', '7',
       '0', '2', '', '', '', '', '', '', '2', '3', '', '', '1', '8', '8',
       '8', '9', '6', '', '', '', '', '0', '7', 'C', 'C', '6', '0', '',
       '', '7', 'A', 'E', 'C', '7', 'F', '', '', 'C', 'A', '', '', '', ''],
      dtype='<U2')

### Now xor'ing the values of the key we got with each cypher text

By doing this we will be able to get a sight of each of the real messeges, and the rest can be guessed.

In [493]:
def messagebreak(c, m, key, index):
    for i in range(len(key)):
        if(key[i] != ''):
            x = XOR(key[i], c[index][i])
            m[i] = x
    return m

In [494]:
#Initializing the messages to zeros
message0 = np.zeros(58, dtype = '<U2')
message1 = np.zeros(58, dtype = '<U2')
message2 = np.zeros(58, dtype = '<U2')
message3 = np.zeros(58, dtype = '<U2')
message4 = np.zeros(58, dtype = '<U2')
message5 = np.zeros(58, dtype = '<U2')

In [495]:
#Now getting the messages according to the part of the key values w got.
message0 = messagebreak(c, message0, key, 0)
message1 = messagebreak(c, message1, key, 1)
message2 = messagebreak(c, message2, key, 2)
message3 = messagebreak(c, message3, key, 3)
message4 = messagebreak(c, message4, key, 4)
message5 = messagebreak(c, message5, key, 5)

#### The messages in hexadecimals

In [496]:
def realmessage(message, mnew):
    for i in range(0, 29):
        if(message[i*2] != ''):
            hexa = message[i*2] + message[(i*2) + 1]
            # Convert the hexadecimal values to integers
            int_value = int(hexa, 16)
            
            # Use the integers to convert to characters
            char = chr(int_value)
            
            #checking if the char is a real char or space then add it
            if((char.isalpha()) or (char.isspace())):
                #add the value
                mnew[i] = char
        else:
            mnew[i] = '-'
    return mnew

In [497]:
m0 = np.zeros(29, dtype = '<U2')
m1 = np.zeros(29, dtype = '<U2')
m2 = np.zeros(29, dtype = '<U2')
m3 = np.zeros(29, dtype = '<U2')
m4 = np.zeros(29, dtype = '<U2')
m5 = np.zeros(29, dtype = '<U2')

In [498]:
#getting the messages.
m0 = realmessage(message0, m0)
m0 = ''.join(map(str, m0))

m1 = realmessage(message1, m1)
m1 = ''.join(map(str, m1))

m2 = realmessage(message2, m2)
m2 = ''.join(map(str, m2))

m3 = realmessage(message3, m3)
m3 = ''.join(map(str, m3))

m4 = realmessage(message4, m4)
m4 = ''.join(map(str, m4))

m5 = realmessage(message5, m5)
m5 = ''.join(map(str, m5))

In [499]:
#Printing the messages.
print(m0)
print(m1)
print(m2)
print(m3)
print(m4)
print(m5)

-u-er o----ns --eed----
-s-htwo --- -r a--h n----
-e- sec---t-odi-- u- ---
-e-r re---t-ne --m  - l- --
-p-te y---t-yst--ser- ---
- - all --- - se--r  - ---


==========================================================================================================================
After getting the messages, it seems like there are some spaces not in the right place, but also there are some words that appears correctly fine, so the next step is trying to geussing what could be the real messages

# The message can be, after guessing

buffer overruns are dangerous  

use two factor authentication

read secure coding guidlines

never resuse one timepad keys

update your systems regularly

i shall write secure software